name: Get previous day market data
on:
  schedule:
    - cron: "31 13 * * 1-5"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous day market data
        run: |
          curl --request POST \
          --url 'https://api.moontimers.com/api/gme_data' \
          --header 'Authorization: Bearer ${{ secrets.TICKER_ACTION_KEY }}'
